import { SITE } from './emit-html.js';

/*
 * The landing page and the blog index are fixed rows — their cadence and
 * priority are editorial constants, not something derivable from a post. Only
 * the post rows come from content/, and drafts are excluded because they carry
 * <meta robots="noindex">: listing a page in the sitemap while asking not to
 * have it indexed sends Google two contradictory signals.
 */
const FIXED = [
  { loc: `${SITE}/`, lastmod: '2026-08-11', changefreq: 'monthly', priority: '1.0' },
  { loc: `${SITE}/blog/`, lastmod: '2026-08-11', changefreq: 'weekly', priority: '0.7' },
];

const row = ({ loc, lastmod, changefreq, priority }) => `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;

export function emitSitemap(posts) {
  const rows = [
    ...FIXED,
    ...posts
      .filter((p) => !p.frontmatter.draft)
      .map((p) => ({
        loc: `${SITE}/blog/${p.slug}/`,
        lastmod: p.date,
        changefreq: 'yearly',
        priority: '0.6',
      })),
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/build-content.js — do not edit.
     The landing page is a single document: its in-page sections (#ask, #taste,
     #friends, #get) are deliberately NOT listed, since duplicate-content signals
     for the same URL hurt more than they help. The blog pages are real,
     separately-addressable documents, so they are. Drafts are excluded. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${rows.map(row).join('\n')}
</urlset>
`;
}
