import path from 'node:path';

/*
 * Emits src/content/generated/posts.js.
 *
 * Images become real static `import` statements rather than import.meta.glob:
 * an import of a deleted file fails the build, where glob would hand back
 * undefined and ship a broken <img>.
 */

const GENERATED_DIR = path.join(process.cwd(), 'src', 'content', 'generated');

/* Marks a value that must appear in the output as a bare JS identifier (an
   imported binding) rather than as a quoted string. */
const raw = (identifier) => ({ __raw: identifier });

const identifierFor = (relPath) =>
  `img_${relPath.replace(/\.[a-z0-9]+$/i, '').replace(/[^a-zA-Z0-9]+/g, '_')}`;

/* JSON.stringify produces valid JS string literals and leaves curly quotes,
   em dashes and “...?” untouched, which is what the copy round-trip asserts. */
function serialize(value, indent = 2) {
  const pad = ' '.repeat(indent);
  if (value === null || value === undefined) return 'undefined';
  if (typeof value === 'object' && value.__raw) return value.__raw;
  if (Array.isArray(value)) {
    if (!value.length) return '[]';
    return `[\n${value.map((v) => `${pad}  ${serialize(v, indent + 2)}`).join(',\n')}\n${pad}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value).filter(([, v]) => v !== undefined);
    if (!entries.length) return '{}';
    return `{\n${entries
      .map(([k, v]) => `${pad}  ${JSON.stringify(k)}: ${serialize(v, indent + 2)}`)
      .join(',\n')}\n${pad}}`;
  }
  return JSON.stringify(value);
}

export function emitPosts(posts, venues) {
  const imports = new Map(); // identifier -> import specifier

  const importFor = (absPath) => {
    const specifier = path
      .relative(GENERATED_DIR, absPath)
      .split(path.sep)
      .join('/');
    const id = identifierFor(path.relative(path.join(process.cwd(), 'content'), absPath).split(path.sep).join('/'));
    imports.set(id, specifier);
    return raw(id);
  };

  const venueValue = (key) => {
    const v = venues[key];
    return {
      name: v.name,
      logo: importFor(v.logoPath),
      bravoUrl: v.bravoUrl,
      street: v.street,
      locality: v.locality,
      mapUrl: v.mapUrl,
      site: v.site,
      siteUrl: v.siteUrl,
    };
  };

  const body = posts.map((p) => ({
    slug: p.slug,
    category: p.frontmatter.category,
    draft: p.frontmatter.draft || undefined,
    title: p.frontmatter.title,
    crumb: p.crumb,
    date: p.date,
    dateLabel: p.dateLabel,
    excerpt: p.excerpt,
    hero: importFor(p.heroAbs),
    heroAlt: p.frontmatter.heroAlt,
    venue: p.frontmatter.venue ? venueValue(p.frontmatter.venue) : undefined,
    content: p.content.map((block) =>
      block.type === 'figure'
        ? {
          type: 'figure',
          src: importFor(block.abs),
          alt: block.alt,
          aspect: block.aspect,
          focus: block.focus,
          width: block.width,
          height: block.height,
        }
        : block,
    ),
  }));

  /* serialize first so every importFor() has run and `imports` is complete */
  const serialized = serialize(body, 0);
  const importLines = [...imports.entries()]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([id, spec]) => `import ${id} from '${spec}';`)
    .join('\n');

  return `/*
 * GENERATED by scripts/build-content.js from content/posts/**. Do not edit.
 *
 * Edit the Markdown instead:  content/posts/<slug>/index.md
 * Regenerate with:            npm run content   (or just run dev/build)
 */
${importLines}

export const POSTS = ${serialized};
`;
}
