/*
 * Emits src/content/generated/venues.js.
 *
 * A second, deliberately tiny generated module, separate from posts.js because
 * posts.js imports .webp files — which makes it unimportable from a Vercel
 * Function running under plain Node. This one is data only, so api/reviews.js
 * can resolve a venue key to its Place ID without shipping the venue's logo,
 * or the whole article set, into the function bundle.
 *
 * It carries the place ID and the name, and nothing else. Place IDs are the one
 * piece of Places content Google exempts from its caching restrictions; review
 * content is never written here or anywhere else.
 */
export function emitVenues(venues) {
  const entries = Object.entries(venues)
    .filter(([, v]) => v.googlePlaceId)
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([key, v]) => `  ${JSON.stringify(key)}: { name: ${JSON.stringify(v.name)}, googlePlaceId: ${JSON.stringify(v.googlePlaceId)} },`)
    .join('\n');

  return `/*
 * GENERATED by scripts/build-content.js from content/venues/*.yml. Do not edit.
 *
 * Venues with Google review integration enabled, keyed by their filename in
 * content/venues/. Only venues that declare a googlePlaceId appear here.
 *
 * Imported by api/reviews.js (a Vercel Function), so this module must stay free
 * of asset imports and of anything browser-specific.
 */
export const VENUE_PLACES = {
${entries}
};

/** @returns {string | undefined} the Google Place ID, if this venue has one */
export const placeIdFor = (venueKey) => VENUE_PLACES[venueKey]?.googlePlaceId;
`;
}
